CompresJSON/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CompresJSON.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home

        [CompressResult]
        public JsonResult Index()
        {
            var rc = new Dictionary<string, object>();

            var str = "akjsfl;asjdf;lasjd fl;jaskldfjalsdjfklsjfdklsjfklsfdjl";

            var result = Compressor.Compress(str);
            var decoded = Compressor.Decompress(result);

            var test1 = Compressor.Compress(str, CompressionMethod.LZ77, EncodingMethod.Base64);
            var test2 = Compressor.Compress(str, CompressionMethod.LZ77, EncodingMethod.UTF8);

            rc[test1.encodingMethod.ToString()] = test1.encodedOutput;
            rc[test2.encodingMethod.ToString()] = test2.encodedOutput;

            rc["decode1"] = Compressor.Decompress(test1).decompressedOutput;
            //rc["decode2"] = Compressor.Decompress(test2).decompressedOutput;

            return Json(rc, JsonRequestBehavior.AllowGet);
        }

        [CompressResult]
        public JsonResult compressWithFilter()
        {
            Dictionary<string, object> rc = new Dictionary<string, object>();

            for (int i = 0; i < 10000; i++)
            {
                rc[i.ToString()] = "askdljfaklsdjfklsafjkaklsafljk";
            }

            return Json(rc, JsonRequestBehavior.AllowGet);
        }

        [CompressResult]
        public JsonResult compressManually(string str)
        {
            var result = Compressor.Compress(str, CompressionMethod.LZ77, EncodingMethod.ASCII);

            return Json(result.encodedOutput, JsonRequestBehavior.AllowGet);
        }

        [Decompress]
        public JsonResult decompress(string str)
        {

            return Json(str);
        }
    }
}

CompresJSON/Controllers/ReceiverController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace CompresJSON.Controllers
{
    public class ReceiverController : Controller
    {
        // GET: Receiver
        public JsonResult Index(string a, string c)
        {
            Stream req = Request.InputStream;
            req.Seek(0, System.IO.SeekOrigin.Begin);
            string httpbody = new StreamReader(req).ReadToEnd();
            httpbody = Encrypter.Decrypt(httpbody);

            Dictionary<string, string> data = Converter.QueryStringToDictionary(httpbody);
            return Json(data);



            //var decryptedHTTPBody = GetDocumentContents(Request);

            //Dictionary<string, object> data = new Dictionary<string, object>();
            //data.redirectToAction = a;
            //data.redirectToController = c;

            //foreach (var key in Request.Form.AllKeys)
            //{
            //    data[key] = Request.Form[key];
            //}
            //foreach (var key in Request.QueryString.AllKeys)
            //{
            //    data[key] = Request.QueryString[key];
            //}

            //return RedirectToAction(data.redirectToAction, new RouteValueDictionary(data));
        }

        public JsonResult LookAtUser(User user)
        {
            return Json(user, JsonRequestBehavior.AllowGet);
        }

        public ActionResult sendEncryptedData()
        {
            return View();
        }

        private string GetDocumentContents(System.Web.HttpRequestBase Request)
        {
            string documentContents;
            using (Stream receiveStream = Request.InputStream)
            {
                using (StreamReader readStream = new StreamReader(receiveStream, Encoding.UTF8))
                {
                    documentContents = readStream.ReadToEnd();
                }
            }
            return documentContents;
        }
    }

    public class User
    {
        public int UserID { get; set; }
        public DateTime dob { get; set; }
    }
}

CompresJSON/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CompresJSON.Controllers
{
    public class TestController : Controller
    {
        // GET: Tests
        public ActionResult Index()
        {
            return View();
        }
    }
}

CompresJSON/Views/Receiver/sendEncryptedData.cshtml
@{
    ViewBag.Title = "sendEncryptedData";
}

<h2>sendEncryptedData</h2>

@using (Html.BeginForm("Index", "Receiver", FormMethod.Post))
{
    
    @Html.TextBox("encryptedJSON")
    @Html.TextBox("foo")
    <button type="submit"></button>
}

CompresJSON/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

CompresJSON/Views/Test/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<a onclick="go('', false)" class="btn btn-lg">normal</a>
<a onclick="go('deflate', false)" class="btn btn-lg">deflate</a>
<a onclick="go('gzip', false)" class="btn btn-lg">gzip</a>
<br /><br />
<a onclick="go('', true)" class="btn btn-lg">normal</a>
<a onclick="go('deflate', true)" class="btn btn-lg">deflate</a>
<a onclick="go('gzip',true)" class="btn btn-lg">gzip</a>

<pre id="json"></pre>

<br /><br />
<input id="ccompress" />
<a onclick="ccompress()">c compress</a>

<pre id="ccompressJson"></pre>

<script>
    function ccompress() {

        $('#ccompressJson').empty();
        $.ajax({
            url: "@Url.Action("compressManually", "Home")",
            data: { "str": $('#ccompress').val() },
            type: "POST"
        }).done(function (result) {

            $('#ccompressJson').html(result);
        });
    }

    function go(compressionmethod, https) {
        $('#json').empty();

        var url = "";

        if (https) {
            url = "https://localhost:44300/Home/compressWithFilter"
        }
        else {
            url = '@Url.Action("compressWithFilter", "Home")';
        }

        var ajaxParams = {
            accepts: 'text/html',
            async: true,
            cache: false,
            contentType: 'text/html',
            url: url,
            dataType: "jsonp",
            type: 'POST',
            beforeSend: function (jqXHR) {
                // set request headers here rather than in the ajax 'headers' object
                //jqXHR.setRequestHeader('Accept-Encoding', 'deflate');
                jqXHR.setRequestHeader('JSON-Accept-Encoding', compressionmethod);
                jqXHR.setRequestHeader('JSON-Security', 'aes');
            },
            success: function (data, textStatus, jqXHR) {
                console.log('Yay!');
                $('#json').text(data);
            },
            error: function (jqXHR, textStatus, errorThrown) {
                console.log('Oh no!');
            },
            complete: function (jqXHR, textStatus) {
                console.log(textStatus);
                console.log(jqXHR.status);
                console.log(jqXHR.responseText);

                $('#json').text(jqXHR.responseText);
            }
        };

        $.ajax(ajaxParams);
    }
</script>